// Preview geography only. Completion and availability will come from the API.
export const worlds = [
  {
    slug: "beginner-beach",
    name: "Beginner Beach",
    region: "01",
    theme: "beach",
    subtitle: "Every great adventure starts with a single line.",
    topics: "Variables · Data types · Operators · Output",
    quests: 3,
    npc: "Captain Byte",
    role: "Keeper of first steps",
    x: 49,
    y: 57,
  },
  {
    slug: "loop-village",
    name: "Loop Village",
    region: "02",
    theme: "village",
    subtitle: "A little repetition goes a long way.",
    topics: "Conditions · for · while · do-while",
    quests: 3,
    npc: "The Clockmaker",
    role: "Master of repetition",
    x: 56,
    y: 56,
  },
  {
    slug: "array-forest",
    name: "Array Forest",
    region: "03",
    theme: "forest",
    subtitle: "Find the order hidden among the trees.",
    topics: "Arrays · Indexing · Traversal · Maximum",
    quests: 3,
    npc: "Ranger Index",
    role: "Guardian of the grove",
    x: 43,
    y: 57,
  },
  {
    slug: "oop-canyon",
    name: "OOP Canyon",
    region: "04",
    theme: "canyon",
    subtitle: "Build something greater than its parts.",
    topics: "Classes · Objects · OOP principles",
    quests: 2,
    npc: "The Architect",
    role: "Shaper of blueprints",
    x: 55,
    y: 57,
  },
  {
    slug: "collection-kingdom",
    name: "Collection Kingdom",
    region: "05",
    theme: "kingdom",
    subtitle: "Bring your knowledge together. Claim your crown.",
    topics: "ArrayList · HashMap · Set",
    quests: 2,
    npc: "The Archivist",
    role: "Keeper of collections",
    x: 48,
    y: 61,
  },
];
